### PR TITLE
fix(experiments): properly record metadata

### LINKED ISSUE #611: Experiments not properly recording dev dependencies for NPM
The NPM detectors record components with the following function:

https://github.com/microsoft/component-detection/blob/c8c1cc74e33835536ac5b78263a7b806194941fb/src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentUtilities.cs#L30-L40

`newComponent` should have the `DevelopmentDependency` property set to true, but it is not. However, dev dependencies are still properly registered. When the graph is created, the dev dependency info is propagated:

https://github.com/microsoft/component-detection/blob/c8c1cc74e33835536ac5b78263a7b806194941fb/src/Microsoft.ComponentDetection.Common/DependencyGraph/ComponentRecorder.cs#L221-L238

So, the dependency graph has the proper value, but the component recorder's `DetectedComponent`, which is used for experiments, does not have `DevelopmentDependency` set.

I'm not entirely sure this applies to just NPM, I think all `DetectedComponents` don't properly have the development dependency flag set. Perhaps the `ComponentRecorder` should handle this automatically.

### PR DESCRIPTION
**Pull request by melotic**
`DetectedComponent` has the metadata such as whether the component is a development dependency, and the root components, but this data is not actually set.

Instead, detectors create `DetectedComponent`s with the `TypedComponent`, and the metadata is passed into `ComponentRecorder` which then appends the component to the graph with proper metadata.

This switches experiments from using `DetectedComponent` to `ScannedComponent` by using the `IGraphTranslationService` to parse the data from the `ComponentRecorder`.

Fixes #611

### CODE REVIEW

File: src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs [hunk 1]
```diff
@@ -109,7 +109,7 @@ public async Task<DetectorProcessingResult> ProcessDetectorsAsync(IDetectionArgu
                     exitCode = resultCode;
                 }
 
-                this.experimentService.RecordDetectorRun(detector, detectedComponents);
+                this.experimentService.RecordDetectorRun(detector, componentRecorder, detectionArguments);
```
Comment (melotic) [inline src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingService.cs:112]: This fixes this exception: 

```
[12:43:34 DBG] The path: /home/jamie/scratch/dotnet/project-assets/project-assets.csproj could not be resolved relative to the root file:///D:/a/component-detection/component-detection/test/Microsoft.ComponentDetection.VerificationTests/resources/
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Microsoft.ComponentDetection.Orchestrator.Services.GraphTranslation.DefaultGraphTranslationService.MakeFilePathsRelative(ILogger logger, DirectoryInfo rootDirectory, HashSet`1 filePaths) in D:\a\component-detection\component-detection\src\Microsoft.ComponentDetection.Orchestrator\Services\GraphTranslation\DefaultGraphTranslationService.cs:line 215
```

which only happens on Windows because the `URI` class does not parse Linux paths on Windows:

https://github.com/microsoft/component-detection/blob/dae150a3b42770e7aadcf844f49a82d603b768d4/test/Microsoft.ComponentDetection.VerificationTests/resources/nuget/project-assets/project.assets.json#L4608-L4612

Tested on Windows and Ubuntu and doesn't seem to cause issues.

**Comment by melotic** [comment]
<details>
<summary>Sample diff</summary>

```json
{
  "AddedIds": [],
  "RemovedIds": [
    "test 1.0.0 - Npm"
  ],
  "DevelopmentDependencyChanges": [
    {
      "Id": "@sinclair/typebox 0.28.17 - Npm",
      "OldValue": false,
      "NewValue": true
    }
  ],
  "AddedRootIds": {
    "express 4.18.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "ms 2.0.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "body-parser 1.20.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "function-bind 1.1.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "inherits 2.0.4 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "safer-buffer 2.1.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "bytes 3.1.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "ipaddr.js 1.9.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "on-finished 2.4.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "http-errors 2.0.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "ms 2.1.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "get-intrinsic 1.2.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "negotiator 0.6.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "encodeurl 1.0.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "toidentifier 1.0.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "@sinclair/typebox 0.28.17 - Npm": [
      "@sinclair/typebox 0.28.17 - Npm"
    ],
    "ee-first 1.1.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "object-inspect 1.12.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "parseurl 1.3.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "has 1.0.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "methods 1.1.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "type-is 1.6.18 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "mime 1.6.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "fresh 0.5.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "destroy 1.2.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "forwarded 0.2.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "qs 6.11.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "etag 1.8.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "proxy-addr 2.0.7 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "merge-descriptors 1.0.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "vary 1.1.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "debug 2.6.9 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "send 0.18.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "raw-body 2.5.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "array-flatten 1.1.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "escape-html 1.0.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "content-disposition 0.5.4 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "media-typer 0.3.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "serve-static 1.15.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "has-symbols 1.0.3 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "mime-types 2.1.35 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "side-channel 1.0.4 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "content-type 1.0.5 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "call-bind 1.0.2 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "depd 2.0.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "mime-db 1.52.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "cookie 0.5.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "range-parser 1.2.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "setprototypeof 1.2.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "cookie-signature 1.0.6 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "unpipe 1.0.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "has-proto 1.0.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "finalhandler 1.2.0 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "utils-merge 1.0.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "path-to-regexp 0.1.7 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "safe-buffer 5.2.1 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "iconv-lite 0.4.24 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "accepts 1.3.8 - Npm": [
      "express 4.18.2 - Npm"
    ],
    "statuses 2.0.1 - Npm": [
      "express 4.18.2 - Npm"
    ]
  },
  "RemovedRootIds": {}
}
```
</details>

File: src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs [hunk 2]
```diff
@@ -212,7 +212,7 @@ private HashSet<string> MakeFilePathsRelative(ILogger logger, DirectoryInfo root
         {
             try
             {
-                var relativePath = rootUri.MakeRelativeUri(new Uri(path)).ToString();
+                var relativePath = rootUri.MakeRelativeUri(new Uri(new Uri("file://"), path)).ToString();
```
Comment (melotic) [inline src/Microsoft.ComponentDetection.Orchestrator/Services/GraphTranslation/DefaultGraphTranslationService.cs:215]: This fixes this exception: 

```
[12:43:34 DBG] The path: /home/jamie/scratch/dotnet/project-assets/project-assets.csproj could not be resolved relative to the root file:///D:/a/component-detection/component-detection/test/Microsoft.ComponentDetection.VerificationTests/resources/
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Microsoft.ComponentDetection.Orchestrator.Services.GraphTranslation.DefaultGraphTranslationService.MakeFilePathsRelative(ILogger logger, DirectoryInfo rootDirectory, HashSet`1 filePaths) in D:\a\component-detection\component-detection\src\Microsoft.ComponentDetection.Orchestrator\Services\GraphTranslation\DefaultGraphTranslationService.cs:line 215
```

which only happens on Windows because the `Uri` class does not parse Linux paths on Windows:

https://github.com/microsoft/component-detection/blob/dae150a3b42770e7aadcf844f49a82d603b768d4/test/Microsoft.ComponentDetection.VerificationTests/resources/nuget/project-assets/project.assets.json#L4608-L4612

Tested on Windows and Ubuntu and doesn't seem to cause issues.

File: src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs [hunk 3]
```diff
@@ -1,44 +1,63 @@
...
         this.experiments = new ConcurrentDictionary<IExperimentConfiguration, ExperimentResults>(
             configs.ToDictionary(config => config, _ => new ExperimentResults()));
         this.experimentProcessors = experimentProcessors;
+        this.graphTranslationService = graphTranslationService;
         this.logger = logger;
     }
 
     /// <inheritdoc />
-    public void RecordDetectorRun(IComponentDetector detector, IEnumerable<DetectedComponent> components)
+    public void RecordDetectorRun(IComponentDetector detector, ComponentRecorder componentRecorder, IDetectionArguments detectionArguments)
```
Comment (JamieMagee) [inline src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs:47]: nit: use interfaces in method signatures
```suggestion
    public void RecordDetectorRun(IComponentDetector detector, IComponentRecorder componentRecorder, IDetectionArguments detectionArguments)
```

**Review by JamieMagee — APPROVED** [review]

File: src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs (hunk 3 above)
Comment (melotic) [reply src/Microsoft.ComponentDetection.Orchestrator/Experiments/ExperimentService.cs:47]: We cannot pass the interface, because `DetectorProcessingResult` requires `ComponentRecorder`, not `IComponentRecorder`

https://github.com/microsoft/component-detection/blob/262fa8857d16fa133264678db17d8b1f5229617c/src/Microsoft.ComponentDetection.Orchestrator/Services/DetectorProcessingResult.cs#L13
