### PR TITLE
Normalize Podfile.lock Git Uris to support git@

### LINKED ISSUE #50: Podfile.lock not scanned if ssh git URL present
We have a declaration in our Podfile:
```
  pod 'XMPPFramework', :git => 'git@git.datcon.co.uk:accession/iOS/XMPPFramework.git', :branch => 'master'
 ```

When the resultant `Podfile.lock` is read by Component Governance, this causes an exception and Component Governance fails to detect any of the components declared:

```
[VERBOSE] Could not read component details from file C:\__w\1\s\component-detection-inputs\Podfile.lock 
[INFO] LogFailedReadingFile logged UriFormatException: Invalid URI: The URI scheme is not valid. 
```
(Taken from ADO pipeline log at [Pipelines - Run 20220119.1 logs (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmsazuredev%2FAzureForOperators%2F_build%2Fresults%3FbuildId%3D83031%26view%3Dlogs%26j%3Dd5c48638-dd90-5d5e-9353-04b987e50767%26t%3Dcbcd144b-7330-5698-b10d-ab954a18ce70%26l%3D78&data=04%7C01%7Canthayward%40microsoft.com%7C275b808a9c96457cf82408d9dc81bf46%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637783272119333841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mootTrzgM57q4kAzaIgV0not3HIQs4pWiBS%2BTZ6B%2Bp4%3D&reserved=0))
 
If we change the git ssh URL to an https URL then it is fine.

### PR DESCRIPTION
**Pull request by cobya**
Resolves #50 by normalizing all git@ references to https:// so Uri creation does not fail.

### CODE REVIEW

File: src/Microsoft.ComponentDetection.Detectors/cocoapods/PodComponentDetector.cs [hunk 1]
```diff
@@ -405,5 +407,17 @@ private static (Pod pod, string key, DetectedComponent detectedComponent)[] Read
...
             .ToArray();
         }
+
+        private static string NormalizePodfileGitUri(string gitOption)
+        {
+            // Podfiles can be built using git@ references to .git files, but this is not a valid Uri
+            // schema. Normalize to https:// so Uri creation doesn't fail
+            if (gitOption.StartsWith("git@", StringComparison.OrdinalIgnoreCase))
+            {
+                return $"https://{gitOption[4..]}";
```
Comment (grvillic) [inline src/Microsoft.ComponentDetection.Detectors/cocoapods/PodComponentDetector.cs:417]: nit: Why not using [substring](https://docs.microsoft.com/en-us/dotnet/api/system.string.substring?view=net-6.0)? IMO it makes it more readable.

File: src/Microsoft.ComponentDetection.Detectors/cocoapods/PodComponentDetector.cs [hunk 2]
```diff
@@ -389,6 +390,7 @@ private static (Pod pod, string key, DetectedComponent detectedComponent)[] Read
                     && checkoutOptions.TryGetValue(":commit", out string commitOption))
                 {
                     // Create the Git component
+                    gitOption = NormalizePodfileGitUri(gitOption);
                     typedComponent = new GitComponent(new Uri(gitOption), commitOption);
```
Comment (grvillic) [inline src/Microsoft.ComponentDetection.Detectors/cocoapods/PodComponentDetector.cs:394]: Since this is introducing new values for same components, I think we should bump the detector version.

**Review by grvillic — APPROVED** [review]
