### PR TITLE
don't throw if `engines` property is a string array

### LINKED ISSUE #1385: Npm exception for "vscode" invalid key value
## Bug
NPM detector throwing an exception for a package.json file parsing.

Sample package.json file can be found in [concat-stream/package.json](https://github.com/max-mapper/concat-stream/blob/master/package.json).

  ```json
,
"engines": [
    "node >= 6.0"
  ],
  "main": "index.js",
  "files": [
    "index.js"
  ],
```

## Stack trace
```
System.ArgumentException: Accessed JArray values with invalid key value: "vscode". Int32 array index expected.
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at Microsoft.ComponentDetection.Detectors.Npm.NpmComponentDetector.ProcessIndividualPackageJTokens(String filePath, ISingleFileComponentRecorder singleFileComponentRecorder, JToken packageJToken) in src\Microsoft.ComponentDetection.Detectors\npm\NpmComponentDetector.cs:line 91
   at Microsoft.ComponentDetection.Detectors.Npm.NpmComponentDetector.<>c__DisplayClass17_0.<OnFileFoundAsync>b__0(JToken token) in src\component-detection\src\Microsoft.ComponentDetection.Detectors\npm\NpmComponentDetector.cs:line 66
   at Microsoft.ComponentDetection.Detectors.Npm.NpmComponentDetector.ProcessAllPackageJTokensAsync(String contents, JTokenProcessingDelegate jtokenProcessor) in src\component-detection\src\Microsoft.ComponentDetection.Detectors\npm\NpmComponentDetector.cs:line 73
   at Microsoft.ComponentDetection.Detectors.Npm.NpmComponentDetector.SafeProcessAllPackageJTokensAsync(String sourceFilePath, String contents, JTokenProcessingDelegate jtokenProcessor) in src\Microsoft.ComponentDetection.Detectors\npm\NpmComponentDetector.cs:line 107
```

### PR DESCRIPTION
**Pull request by brettfo**
`package.json` files seen in the wild have had a string array instead of an object for the `engines` property (example [here](https://github.com/Tjatse/ansi-html/blob/25ffe44357aa8f28d00239af61b74baced7510e4/package.json#L29)).  Because of this, anything that pulls in one of these variant packages will fail to generate components.

While `engines` should be an object, this PR allows for this alternate form to allow detection to continue.

Fixes #1385

### CODE REVIEW

File: src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs [hunk 1]
```diff
@@ -88,10 +89,38 @@ protected virtual bool ProcessIndividualPackageJTokens(string filePath, ISingleF
...
+            {
+                if (enginesToken["vscode"] != null)
+                {
+                    containsVsCodeEngine = true;
+                }
+            }
+            else
+            {
+                throw new NotImplementedException($"Unsupported engines token type {enginesToken}");
+            }
```
Comment (JamieMagee) [inline src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs:117]: I'd move `containsVsCodeEngine` up in scope, out of this if/else, and avoid throwing this exception.

**Review by JamieMagee — APPROVED** [review]

File: src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs (hunk 1 above)
Comment (brettfo) [reply src/Microsoft.ComponentDetection.Detectors/npm/NpmComponentDetector.cs]: Done.

**Review by JamieMagee — APPROVED** [review]
